[2023-10-16 08:13:13,460]^;WARNING^;96^;_internal.py^;_log()^; * Debugger is active!
[2023-10-16 08:13:13,461]^;INFO^;96^;_internal.py^;_log()^; * Debugger PIN: 940-296-162
[2023-10-16 08:14:17,858]^;INFO^;14^;app.py^;index()^;
        Error occured in script: 
        [ /home/pradeep.k@zucisystems.com/workspace_working_Repo/DataScience/M4_Project/M1_Application/app.py ] at 
        try block line number: [11] and exception block line number: [13] 
        error message: [We are Testing custom exception]
        
[2023-10-16 08:14:17,858]^;INFO^;15^;app.py^;index()^;We are testing logging module
[2023-10-16 08:14:17,858]^;INFO^;96^;_internal.py^;_log()^;127.0.0.1 - - [16/Oct/2023 08:14:17] "GET / HTTP/1.1" 200 -
[2023-10-16 08:14:18,567]^;INFO^;14^;app.py^;index()^;
        Error occured in script: 
        [ /home/pradeep.k@zucisystems.com/workspace_working_Repo/DataScience/M4_Project/M1_Application/app.py ] at 
        try block line number: [11] and exception block line number: [13] 
        error message: [We are Testing custom exception]
        
[2023-10-16 08:14:18,567]^;INFO^;15^;app.py^;index()^;We are testing logging module
[2023-10-16 08:14:18,567]^;INFO^;96^;_internal.py^;_log()^;127.0.0.1 - - [16/Oct/2023 08:14:18] "GET / HTTP/1.1" 200 -
[2023-10-16 08:14:18,769]^;INFO^;14^;app.py^;index()^;
        Error occured in script: 
        [ /home/pradeep.k@zucisystems.com/workspace_working_Repo/DataScience/M4_Project/M1_Application/app.py ] at 
        try block line number: [11] and exception block line number: [13] 
        error message: [We are Testing custom exception]
        
[2023-10-16 08:14:18,769]^;INFO^;15^;app.py^;index()^;We are testing logging module
[2023-10-16 08:14:18,769]^;INFO^;96^;_internal.py^;_log()^;127.0.0.1 - - [16/Oct/2023 08:14:18] "GET / HTTP/1.1" 200 -
[2023-10-16 08:14:18,904]^;INFO^;14^;app.py^;index()^;
        Error occured in script: 
        [ /home/pradeep.k@zucisystems.com/workspace_working_Repo/DataScience/M4_Project/M1_Application/app.py ] at 
        try block line number: [11] and exception block line number: [13] 
        error message: [We are Testing custom exception]
        
[2023-10-16 08:14:18,904]^;INFO^;15^;app.py^;index()^;We are testing logging module
[2023-10-16 08:14:18,904]^;INFO^;96^;_internal.py^;_log()^;127.0.0.1 - - [16/Oct/2023 08:14:18] "GET / HTTP/1.1" 200 -
[2023-10-16 08:14:19,037]^;INFO^;14^;app.py^;index()^;
        Error occured in script: 
        [ /home/pradeep.k@zucisystems.com/workspace_working_Repo/DataScience/M4_Project/M1_Application/app.py ] at 
        try block line number: [11] and exception block line number: [13] 
        error message: [We are Testing custom exception]
        
[2023-10-16 08:14:19,037]^;INFO^;15^;app.py^;index()^;We are testing logging module
[2023-10-16 08:14:19,037]^;INFO^;96^;_internal.py^;_log()^;127.0.0.1 - - [16/Oct/2023 08:14:19] "GET / HTTP/1.1" 200 -
[2023-10-16 08:14:19,172]^;INFO^;14^;app.py^;index()^;
        Error occured in script: 
        [ /home/pradeep.k@zucisystems.com/workspace_working_Repo/DataScience/M4_Project/M1_Application/app.py ] at 
        try block line number: [11] and exception block line number: [13] 
        error message: [We are Testing custom exception]
        
[2023-10-16 08:14:19,173]^;INFO^;15^;app.py^;index()^;We are testing logging module
[2023-10-16 08:14:19,173]^;INFO^;96^;_internal.py^;_log()^;127.0.0.1 - - [16/Oct/2023 08:14:19] "GET / HTTP/1.1" 200 -
[2023-10-16 08:14:19,355]^;INFO^;14^;app.py^;index()^;
        Error occured in script: 
        [ /home/pradeep.k@zucisystems.com/workspace_working_Repo/DataScience/M4_Project/M1_Application/app.py ] at 
        try block line number: [11] and exception block line number: [13] 
        error message: [We are Testing custom exception]
        
[2023-10-16 08:14:19,355]^;INFO^;15^;app.py^;index()^;We are testing logging module
[2023-10-16 08:14:19,356]^;INFO^;96^;_internal.py^;_log()^;127.0.0.1 - - [16/Oct/2023 08:14:19] "GET / HTTP/1.1" 200 -
[2023-10-16 08:14:42,238]^;INFO^;96^;_internal.py^;_log()^; * Detected change in '/home/pradeep.k@zucisystems.com/workspace_working_Repo/DataScience/M4_Project/M1_Application/app.py', reloading
